# -*- mode: ruby -*-
# vi: set ft=ruby :
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

box = {
  #:virtualbox => { :name => 'elastic/ubuntu-18.04-x86_64', :version => '20191013.0.0'},
  :libvirt => { :name => 'generic/ubuntu2204', :version => '4.1.12'}
}

require 'yaml'
pdf = File.dirname(__FILE__) + '/config/default.yml'
nodes = YAML.load_file(pdf)

provider = (ENV['VAGRANT_DEFAULT_PROVIDER'] || :libvirt).to_sym
puts "[INFO] Provider: #{provider} "


Vagrant.configure("2") do |config|
  config.vm.box =  box[provider][:name]
  config.vm.box_version = box[provider][:version]
  config.ssh.insert_key = false

  config.vm.provider 'libvirt' do |v|
    v.nested = true
    v.cpu_mode = 'host-passthrough'
    v.management_network_address = "192.168.121.0/27"
    v.random_hostname = true
  end

  sync_type = "virtualbox"
  if provider == :libvirt
    sync_type = "nfs"
  end

  nodes.each do |node|
    config.vm.define node['name'] do |nodeconfig|
      nodeconfig.vm.hostname = node['name']
      nodeconfig.vm.network :private_network, :ip => node['ip'], :type => :static
      nodeconfig.vm.provider 'libvirt' do |v|
        v.memory = node['memory']
        v.cpus = node['cpus']
      end
      nodeconfig.vm.provision 'shell', privileged: false do |sh|
        sh.path = "network.sh"
      end
    end
  end
end
